In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import math
import os
import re
import pickle

In [2]:
ACTION_DATA = 'JData_Action_201602.csv'
USER_FILE = 'JData_User.csv'
PRODUCT_FILE = 'JData_Product.csv'
COMMENT_FILE = 'JData_Comment.csv'

In [3]:
#25号到29号购买过第8类商品的用户作为测试集
def Action_useful_user():
    dump_path = './cache/Action_useful_data'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        dataset = pd.read_csv(ACTION_DATA)[['user_id','sku_id','time','cate','type']]
        #2-25号到29号买了第八类商品,并且25号前7天有第8类商品浏览记录的用户保存下来
        test_sample= dataset[(dataset['time']>'2016-02-25 00:00:00')&(dataset['type']==4)&(dataset['cate']==8)][['user_id','sku_id']].drop_duplicates()
        #25号前7天浏览过第八类商品的用户
        sample_data = dataset[(dataset['time']<'2016-02-25 00:00:00')&(dataset['time']>'2016-02-18 00:00:00')&(dataset['cate']==8)].user_id.to_frame().drop_duplicates()
        test_sample = pd.merge(sample_data,test_sample,on='user_id',how='left')
        test_sample = test_sample[test_sample.sku_id.notnull()]
        test_sample.to_csv('test_dataset.csv',index=False)
        #删除25号之前购买过第八类商品的用户
        dataset = dataset[dataset['time']<'2016-02-25 00:00:00']
        delta_user_id = pd.DataFrame(dataset[(dataset['type']==4)&(dataset['cate']==8)]['user_id']).drop_duplicates()
        delta_user_id['label'] = 0
        all_user_id = pd.merge(dataset,delta_user_id,on='user_id',how='left')
        all_user_id = pd.DataFrame(all_user_id[all_user_id.label.isnull()]['user_id']).drop_duplicates()

#         all_user_id = dataset.drop(delta_user_id.user_id.isin(dataset.user_id),axis=0)
#         all_user_id = pd.DataFrame(all_user_id['user_id']).drop_duplicates()
        df = pd.merge(all_user_id,dataset,on='user_id',how='left')
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [44]:
# dataset = pd.read_csv(ACTION_DATA)[['user_id','sku_id','time','cate','type']]
#         #2-25号到29号买了第八类商品,并且25号前7天有第8类商品浏览记录的用户保存下来
# test_sample= dataset[(dataset['time']>'2016-02-25 00:00:00')&(dataset['type']==4)&(dataset['cate']==8)][['user_id','sku_id']].drop_duplicates()
# #25号前7天浏览过第八类商品的用户
# sample_data = dataset[(dataset['time']<'2016-02-25 00:00:00')&(dataset['time']>'2016-02-18 00:00:00')&(dataset['cate']==8)].user_id.to_frame().drop_duplicates()
# test_sample = pd.merge(sample_data,test_sample,on='user_id',how='left')
# test_sample = test_sample[test_sample.sku_id.notnull()]
test_sample.to_csv('test_dataset.csv',index=False)

In [43]:
Action_useful_user()

          user_id  sku_id                 time  cate  type
0        263587.0   72348  2016-01-31 23:59:08     5     1
1        263587.0  127189  2016-01-31 23:59:48     5     1
2        263587.0  157009  2016-02-01 00:01:44     5     1
3        263587.0  132879  2016-02-01 00:03:41     5     1
4        263587.0    2100  2016-02-05 17:02:53     4     1
5        263587.0   43109  2016-02-05 17:03:04     4     1
6        263587.0   43109  2016-02-12 17:15:59     4     1
7        263587.0  157009  2016-02-12 17:17:59     5     1
8        263587.0  127189  2016-02-12 17:18:36     5     1
9        263587.0   49474  2016-02-12 17:18:57     5     1
10       263587.0   86551  2016-02-12 17:19:37     5     1
11       263587.0   42497  2016-02-12 17:19:52     5     1
12       263587.0  164532  2016-02-12 17:20:17     5     1
13       263587.0  147740  2016-02-12 17:21:35     5     1
14       263587.0  107611  2016-02-12 17:22:40     5     1
15       263587.0  125188  2016-02-12 17:23:11     5     1
16       263587.0  126791  2016-02-12 17:23:58     5     1
17       263587.0    2100  2016-02-12 17:25:40     4     1
18       263587.0    2100  2016-02-12 17:25:52     4     1
19       263587.0   70491  2016-02-12 17:28:04     6     1
20       263587.0    2100  2016-02-16 01:46:17     4     1
21       263587.0  137805  2016-02-17 02:04:39     4     1
22       263587.0  113494  2016-02-17 02:05:18     4     1
23       263587.0   30199  2016-02-17 02:05:41     5     1
24       263587.0   73696  2016-02-17 02:06:19     4     1
25       263587.0  125188  2016-02-17 02:14:05     5     1
26       263587.0  126791  2016-02-17 02:14:35     5     1
27       263587.0  126791  2016-02-17 02:14:46     5     1
28       263587.0  125188  2016-02-17 02:14:51     5     1
29       263587.0   13931  2016-02-17 02:15:48     5     1
...           ...     ...                  ...   ...   ...
8401396  294389.0  135272  2016-02-24 23:54:46     4     6
8401397  294389.0  135272  2016-02-24 23:54:46     4     6
8401398  294389.0  135272  2016-02-24 23:54:46     4     1
8401399  294389.0  135272  2016-02-24 23:59:14     4     1
8401400  294389.0  135272  2016-02-24 23:59:14     4     1
8401401  261230.0  142477  2016-02-24 23:55:24     8     6
8401402  261230.0  142477  2016-02-24 23:55:24     8     6
8401403  261230.0  142477  2016-02-24 23:55:24     8     1
8401404  261230.0  142477  2016-02-24 23:55:24     8     1
8401405  261230.0  142477  2016-02-24 23:55:24     8     6
8401406  261230.0  142477  2016-02-24 23:55:54     8     1
8401407  261230.0  142477  2016-02-24 23:55:54     8     1
8401408  261230.0  142477  2016-02-24 23:56:54     8     6
8401409  266646.0   30025  2016-02-24 23:57:53     7     6
8401410  266646.0   30025  2016-02-24 23:57:53     7     6
8401411  266646.0   30025  2016-02-24 23:57:53     7     6
8401412  266646.0   30025  2016-02-24 23:57:53     7     6
8401413  266646.0   30025  2016-02-24 23:57:53     7     1
8401414  266646.0   30025  2016-02-24 23:57:53     7     1
8401415  266646.0   99755  2016-02-24 23:59:41     7     1
8401416  266646.0   99755  2016-02-24 23:59:41     7     1
8401417  266646.0   99755  2016-02-24 23:59:41     7     6
8401418  266646.0   99755  2016-02-24 23:59:41     7     6
8401419  266646.0   99755  2016-02-24 23:59:41     7     6
8401420  285579.0   44854  2016-02-24 23:59:05     8     1
8401421  285579.0   44854  2016-02-24 23:59:05     8     6
8401422  285579.0   44854  2016-02-24 23:59:05     8     6
8401423  285579.0   44854  2016-02-24 23:59:05     8     6
8401424  285579.0   44854  2016-02-24 23:59:05     8     1
8401425  295880.0   28276  2016-02-24 23:59:38     4     2

[8401426 rows x 5 columns]

In [5]:
#选择在预测期间前7天与第8类用户有交互的用户（购买过第8类商品的去除）来构造样本
def sample_area_user_id():
    dump_path = './cache/Action_user_id_sample_data'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        df = pd.read_csv(ACTION_DATA)[['user_id','sku_id','type','time','cate']]
        df1 = df
        df1 = pd.DataFrame(df[(df['cate']==8)&(df['time']>'2016-02-23 00:00:00')])
        #购买过第8类商品的用户
        delta_data = df1[df1['type']==4].user_id.to_frame().drop_duplicates()
        delta_data['label'] = 0
        df2 = pd.merge(df1,delta_data,on='user_id',how='left')
        df2 = df2[df2.label.isnull()].user_id.to_frame().drop_duplicates()
        #df2为预测前7天没买过第八类商品但是看过第八类商品的用户
        df = pd.merge(df2,df,on='user_id',how='left')
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [40]:
sample_area_user_id()

          user_id  sku_id  type                 time  cate
0        279627.0   18412     1  2016-02-20 11:17:54     8
1        279627.0   18412     6  2016-02-20 11:17:55     8
2        279627.0   18412     6  2016-02-20 11:17:59     8
3        279627.0   18412     6  2016-02-20 11:20:17     8
4        279627.0   63006     1  2016-02-20 11:20:18     8
5        279627.0   63006     6  2016-02-20 11:20:18     8
6        279627.0   63006     6  2016-02-20 11:20:33     8
7        279627.0   64467     1  2016-02-20 11:20:33     8
8        279627.0   64467     6  2016-02-20 11:20:34     8
9        279627.0   18412     1  2016-02-20 11:21:29     8
10       279627.0   18412     6  2016-02-20 11:21:29     8
11       279627.0   18412     6  2016-02-20 11:22:08     8
12       279627.0   18412     6  2016-02-20 11:22:20     8
13       279627.0   21457     6  2016-02-20 11:22:21     8
14       279627.0   21457     1  2016-02-20 11:22:21     8
15       279627.0   21457     6  2016-02-20 11:22:26     8
16       279627.0   21457     6  2016-02-20 11:22:32     8
17       279627.0   63006     1  2016-02-20 11:22:33     8
18       279627.0   63006     6  2016-02-20 11:22:33     8
19       279627.0   64467     1  2016-02-20 11:22:45     8
20       279627.0   63006     6  2016-02-20 11:22:45     8
21       279627.0   64467     6  2016-02-20 11:22:46     8
22       279627.0   18412     1  2016-02-20 11:22:54     8
23       279627.0   64467     6  2016-02-20 11:22:54     8
24       279627.0   18412     6  2016-02-20 11:22:55     8
25       279627.0   64467     1  2016-02-20 11:40:16     8
26       279627.0   18412     6  2016-02-20 11:40:16     8
27       279627.0   64467     6  2016-02-20 11:40:17     8
28       279627.0   64467     6  2016-02-20 11:40:42     8
29       279627.0   18412     6  2016-02-20 11:40:43     8
...           ...     ...   ...                  ...   ...
5791764  247295.0  140807     6  2016-02-22 22:39:19     8
5791765  247295.0  140807     1  2016-02-22 22:39:49     8
5791766  247295.0  140807     1  2016-02-22 22:39:49     8
5791767  247295.0    6998     1  2016-02-29 23:59:36     8
5791768  247295.0    6998     1  2016-02-29 23:59:36     8
5791769  247295.0    6998     6  2016-02-29 23:59:56     8
5791770  247295.0    6998     6  2016-02-29 23:59:56     8
5791771  300294.0   32876     1  2016-02-29 23:56:52     4
5791772  300294.0   32876     6  2016-02-29 23:56:52     4
5791773  300294.0   32876     1  2016-02-29 23:56:52     4
5791774  300294.0   32876     1  2016-02-29 23:56:52     4
5791775  300294.0   32876     1  2016-02-29 23:56:52     4
5791776  300294.0   32876     6  2016-02-29 23:56:52     4
5791777  300294.0   32876     6  2016-02-29 23:56:52     4
5791778  300294.0  130948     6  2016-02-29 23:57:30     4
5791779  300294.0  130948     6  2016-02-29 23:57:30     4
5791780  300294.0  130948     1  2016-02-29 23:57:30     4
5791781  300294.0  130948     1  2016-02-29 23:57:30     4
5791782  300294.0   32876     1  2016-02-29 23:57:30     4
5791783  300294.0   32876     1  2016-02-29 23:57:30     4
5791784  300294.0   32876     6  2016-02-29 23:57:30     4
5791785  300294.0  117144     6  2016-02-29 23:58:32     4
5791786  300294.0  117144     1  2016-02-29 23:58:32     4
5791787  300294.0  117144     6  2016-02-29 23:58:32     4
5791788  300294.0  117144     1  2016-02-29 23:58:32     4
5791789  300294.0    5825     1  2016-02-29 23:59:41     8
5791790  300294.0    5825     1  2016-02-29 23:59:41     8
5791791  300294.0    5825     6  2016-02-29 23:59:41     8
5791792  300294.0    5825     6  2016-02-29 23:59:41     8
5791793  300294.0    5825     6  2016-02-29 23:59:41     8

[5791794 rows x 5 columns]

In [6]:
#训练集01-31 到02-25号 ,样本区间02-18 00:00:00--02-25 00:00:00,标签区间2016-02-25 00:00:00 --2016-03-01 00:00:00
#保存18号到25号查看了第八类商品的用户，作为样本用户
def create_train_set():
    dump_path = './cache/train_dataset'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df =pickle.load(f)
    else:
#         df = pd.read_csv(ACTION_DATA)[['user_id','sku_id','type','time','cate']]
#         #标签数据
#         df = df[df['time']>'2016-02-25 00:00:00']
#         df = df[(df['cate']==8)&(df['type']==4)][['user_id','sku_id']]
        #去除只在18号到25号登陆，并且购买了商品的用户
        dataset = Action_useful_user()
        df1 = dataset[dataset['time']<'2016-02-25 00:00:00']
        # 02-19 --02-25
        df3 = pd.DataFrame(df1[(df1['time']>'2016-02-18 00:00:00')&(df1['cate']==8)]['user_id']).drop_duplicates()
        df = pd.merge(df3,df1,on='user_id',how='left')
        #删除非第8类商品浏览记录
        df = df[df['cate']==8]
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [26]:
# df = pd.read_csv(ACTION_DATA)[['user_id','sku_id','type','time','cate']]
#         #标签数据
# df = df[df['time']>'2016-02-25 00:00:00']
# df = df[(df['cate']==8)&(df['type']==4)][['user_id','sku_id']]
#         ##去除只在18号到25号登陆，并且购买了商品的用户
# dataset = Action_useful_user()
# df1 = dataset[dataset['time']<'2016-02-25 00:00:00']
#         ##02-18 --02-25
# df3 = pd.DataFrame(df1[(df1['time']>'2016-02-18 00:00:00')&(df1['cate']==8)]['user_id']).drop_duplicates()
# df2 =df3
# df2['label'] = 0
# df2 = pd.merge(df2,df,on='user_id',how='left')
# df2 = df2[df2.label==0][['user_id','sku_id']]
# df2 = df2.astype(int)
# # df2.to_csv('label_dataset.csv',index=False)
# df2

Empty DataFrame
Columns: [user_id, sku_id]
Index: []

In [46]:
create_train_set()

          user_id  sku_id                 time  cate  type
203      296130.0   18412  2016-02-23 12:16:10     8     1
204      296130.0   18412  2016-02-23 12:16:12     8     6
205      296130.0   18412  2016-02-23 12:16:13     8     6
206      296130.0   18412  2016-02-23 12:16:20     8     6
207      296130.0   18412  2016-02-23 12:16:22     8     6
211      217567.0   22387  2016-01-31 23:59:54     8     1
212      217567.0   22387  2016-01-31 23:59:54     8     6
213      217567.0  116489  2016-02-01 00:00:53     8     6
214      217567.0  116489  2016-02-01 00:01:46     8     5
215      217567.0  116489  2016-02-01 00:03:20     8     1
216      217567.0  116489  2016-02-01 00:03:21     8     6
217      217567.0   17470  2016-02-01 00:03:26     8     1
218      217567.0   17470  2016-02-01 00:03:26     8     6
219      217567.0   17470  2016-02-01 00:04:08     8     6
220      217567.0   17470  2016-02-01 00:04:08     8     5
221      217567.0   17470  2016-02-01 00:04:12     8     6
222      217567.0  116489  2016-02-01 00:04:51     8     6
223      217567.0  112332  2016-02-24 22:54:41     8     6
224      217567.0  112332  2016-02-24 22:54:41     8     1
225      217567.0  112332  2016-02-24 22:54:41     8     6
226      217567.0  112332  2016-02-24 22:54:41     8     6
227      217567.0  112332  2016-02-24 22:54:41     8     1
248      214894.0  154732  2016-02-04 02:06:56     8     1
249      214894.0  154732  2016-02-04 02:06:56     8     6
250      214894.0  154732  2016-02-04 02:06:56     8     6
251      214894.0  154732  2016-02-04 02:06:56     8     1
252      214894.0  154732  2016-02-04 02:06:56     8     6
253      214894.0  154732  2016-02-04 02:08:01     8     1
254      214894.0  154732  2016-02-04 02:08:01     8     1
255      214894.0   14163  2016-02-04 20:17:59     8     6
...           ...     ...                  ...   ...   ...
4286982  285410.0   15781  2016-02-24 23:58:18     8     6
4286983  285410.0   73469  2016-02-24 23:58:18     8     1
4286984  285410.0   73469  2016-02-24 23:58:18     8     1
4286985  285410.0   15781  2016-02-24 23:58:18     8     6
4286986  285410.0   73469  2016-02-24 23:58:18     8     6
4286987  285410.0   15781  2016-02-24 23:58:48     8     6
4286988  297671.0   81462  2016-02-24 23:51:06     8     6
4286989  297671.0   81462  2016-02-24 23:51:06     8     1
4286990  297671.0   81462  2016-02-24 23:51:06     8     6
4286991  297671.0   81462  2016-02-24 23:51:06     8     1
4286992  303930.0  154636  2016-02-24 23:54:12     8     1
4286993  303930.0  154636  2016-02-24 23:54:12     8     6
4286994  303930.0  154636  2016-02-24 23:54:12     8     1
4286995  303930.0  154636  2016-02-24 23:54:12     8     6
4286996  303930.0  154636  2016-02-24 23:54:12     8     1
4286997  303930.0  154636  2016-02-24 23:54:12     8     6
4286998  303930.0  154636  2016-02-24 23:54:12     8     1
4287020  261230.0  142477  2016-02-24 23:55:24     8     6
4287021  261230.0  142477  2016-02-24 23:55:24     8     6
4287022  261230.0  142477  2016-02-24 23:55:24     8     1
4287023  261230.0  142477  2016-02-24 23:55:24     8     1
4287024  261230.0  142477  2016-02-24 23:55:24     8     6
4287025  261230.0  142477  2016-02-24 23:55:54     8     1
4287026  261230.0  142477  2016-02-24 23:55:54     8     1
4287027  261230.0  142477  2016-02-24 23:56:54     8     6
4287028  285579.0   44854  2016-02-24 23:59:05     8     1
4287029  285579.0   44854  2016-02-24 23:59:05     8     6
4287030  285579.0   44854  2016-02-24 23:59:05     8     6
4287031  285579.0   44854  2016-02-24 23:59:05     8     6
4287032  285579.0   44854  2016-02-24 23:59:05     8     1

[1489716 rows x 5 columns]

# 构造特征

In [7]:
#用户属性特征
def feat_setup_1():
    dump_path = './cache/feat_setup_1'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        df = create_train_set()
        user_info = pd.read_csv(USER_FILE,encoding='gbk')
        #查看用户完整数据
        df = pd.merge(df,user_info,on='user_id',how='left')
        #用户等级大于2的
        df = df[df['user_lv_cd']>=2]
        #注册日期距离测试第一天的距离（单位：天）
        df['user_reg_tm'] = pd.to_datetime(df['user_reg_tm'],format='%Y-%m-%d')
        df['test_time'] = '2016-02-25'
        df['test_time'] = pd.to_datetime(df['test_time'],format='%Y-%m-%d')
        df['reg_dis'] = (df['test_time'] - df['user_reg_tm']).apply(lambda t:t.total_seconds()/60/60/24)
#         temp = df[['user_id','test_time','user_reg_tm']].drop_duplicates()
#         temp['reg_distance'] = temp.user_reg_tm.apply(lambda t:(temp.test_time -t))
#         temp = temp[['user_id','reg_distance']].drop_duplicates()
#         df['reg_distance'] =df.user_reg_tm.apply(lambda t: (df.test_time-t))  #内存错误
#         df = pd.merge(df,temp,on='user_id',how='left')
#         df = df.drop(['test_time'],axis=1)
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [8]:
feat_setup_1()

,user_id,sku_id,time,cate,type,age,sex,user_lv_cd,user_reg_tm,test_time,reg_dis
0,296130.0,18412,2016-02-23 12:16:10,8,1,16-25岁,2.0,2,2015-11-07,2016-02-25,110.0
1,296130.0,18412,2016-02-23 12:16:12,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,110.0
2,296130.0,18412,2016-02-23 12:16:13,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,110.0
3,296130.0,18412,2016-02-23 12:16:20,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,110.0
4,296130.0,18412,2016-02-23 12:16:22,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,110.0
5,217567.0,22387,2016-01-31 23:59:54,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
6,217567.0,22387,2016-01-31 23:59:54,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
7,217567.0,116489,2016-02-01 00:00:53,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
8,217567.0,116489,2016-02-01 00:01:46,8,5,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
9,217567.0,116489,2016-02-01 00:03:20,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
10,217567.0,116489,2016-02-01 00:03:21,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
11,217567.0,17470,2016-02-01 00:03:26,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
12,217567.0,17470,2016-02-01 00:03:26,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
13,217567.0,17470,2016-02-01 00:04:08,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
14,217567.0,17470,2016-02-01 00:04:08,8,5,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
15,217567.0,17470,2016-02-01 00:04:12,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
16,217567.0,116489,2016-02-01 00:04:51,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
17,217567.0,112332,2016-02-24 22:54:41,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
18,217567.0,112332,2016-02-24 22:54:41,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
19,217567.0,112332,2016-02-24 22:54:41,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
20,217567.0,112332,2016-02-24 22:54:41,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
21,217567.0,112332,2016-02-24 22:54:41,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,3188.0
22,214894.0,154732,2016-02-04 02:06:56,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,1928.0
23,214894.0,154732,2016-02-04 02:06:56,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,1928.0
24,214894.0,154732,2016-02-04 02:06:56,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,1928.0
25,214894.0,154732,2016-02-04 02:06:56,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,1928.0
26,214894.0,154732,2016-02-04 02:06:56,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,1928.0
27,214894.0,154732,2016-02-04 02:08:01,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,1928.0
28,214894.0,154732,2016-02-04 02:08:01,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,1928.0
29,214894.0,14163,2016-02-04 20:17:59,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,1928.0
...,...,...,...,...,...,...,...,...,...,...,...
1489686,285410.0,15781,2016-02-24 23:58:18,8,6,-1,1.0,5,2012-11-18,2016-02-25,1194.0
1489687,285410.0,73469,2016-02-24 23:58:18,8,1,-1,1.0,5,2012-11-18,2016-02-25,1194.0
1489688,285410.0,73469,2016-02-24 23:58:18,8,1,-1,1.0,5,2012-11-18,2016-02-25,1194.0
1489689,285410.0,15781,2016-02-24 23:58:18,8,6,-1,1.0,5,2012-11-18,2016-02-25,1194.0
1489690,285410.0,73469,2016-02-24 23:58:18,8,6,-1,1.0,5,2012-11-18,2016-02-25,1194.0
1489691,285410.0,15781,2016-02-24 23:58:48,8,6,-1,1.0,5,2012-11-18,2016-02-25,1194.0
1489692,297671.0,81462,2016-02-24 23:51:06,8,6,36-45岁,0.0,4,2015-11-12,2016-02-25,105.0
1489693,297671.0,81462,2016-02-24 23:51:06,8,1,36-45岁,0.0,4,2015-11-12,2016-02-25,105.0
1489694,297671.0,81462,2016-02-24 23:51:06,8,6,36-45岁,0.0,4,2015-11-12,2016-02-25,105.0
1489695,297671.0,81462,2016-02-24 23:51:06,8,1,36-45岁,0.0,4,2015-11-12,2016-02-25,105.0
1489696,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,42.0
1489697,303930.0,154636,2016-02-24 23:54:12,8,6,16-25岁,2.0,3,2016-01-14,2016-02-25,42.0
1489698,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,42.0
1489699,303930.0,154636,2016-02-24 23:54:12,8,6,16-25岁,2.0,3,2016-01-14,2016-02-25,42.0
1489700,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,42.0
1489701,303930.0,154636,2016-02-24 23:54:12,8,6,16-25岁,2.0,3,2016-01-14,2016-02-25,42.0
1489702,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,42.0
1489703,261230.0,142477,2016-02-24 23:55:24,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,457.0
1489704,261230.0,142477,2016-02-24 23:55:24,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,457.0
1489705,261230.0,142477,2016-02-24 23:55:24,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,457.0
1489706,261230.0,142477,2016-02-24 23:55:24,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,457.0
1489707,261230.0,142477,2016-02-24 23:55:24,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,457.0
1489708,261230.0,142477,2016-02-24 23:55:54,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,457.0
1489709,261230.0,142477,2016-02-24 23:55:54,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,457.0
1489710,261230.0,142477,2016-02-24 23:56:54,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,457.0
1489711,285579.0,44854,2016-02-24 23:59:05,8,1,36-45岁,0.0,3,2012-11-19,2016-02-25,1193.0
1489712,285579.0,44854,2016-02-24 23:59:05,8,6,36-45岁,0.0,3,2012-11-19,2016-02-25,1193.0
1489713,285579.0,44854,2016-02-24 23:59:05,8,6,36-45岁,0.0,3,2012-11-19,2016-02-25,1193.0
1489714,285579.0,44854,2016-02-24 23:59:05,8,6,36-45岁,0.0,3,2012-11-19,2016-02-25,1193.0
1489715,285579.0,44854,2016-02-24 23:59:05,8,1,36-45岁,0.0,3,2012-11-19,2016-02-25,1193.0

# 用户时间行为特征

In [9]:
def feat_setup_2():
    dump_path = './cache/feat_setup_2'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        dataset = feat_setup_1()
        df = dataset[['user_id','time']]
        #登录天数
        df['time'] = df.time.apply(lambda t:t[:10])
        df = df.drop_duplicates()
        type_dummies = pd.get_dummies(df['time'],prefix=None)
        type_dummies.columns = ['25','24','23','22','21','20','19','18','17','16','15','14','13','12','11','10','9','8','7','6','5','4','3','2','1']
        df1 = pd.concat([df,type_dummies],axis=1)
        df1 = df1.drop(['time'],axis=1)
        df1 = df1.drop_duplicates()
        df1 = df1.groupby('user_id',as_index=False).sum()
        df1['load_days'] = df1.sum(axis=1) - df1['user_id']
        df = pd.merge(dataset,df1,on='user_id',how='left')
        
#         #第一次登录距离预测第一天的距离(天)
#         df['first_time'] = df.groupby('user_id',as_index=False).time.min()
#         df['first_time'] = pd.to_datetime(df['first_time'],format='%Y-%m-%d')
#         df['pre_time'] = '2016-02-26'
#         df['pre_time'] = pd.to_datetime(df['pre_time'],format='%Y-%m-%d')
#         df['first_lo_dis'] = df['pre_time'] - df['first_time']
#         df = df.drop(['time','pre_time'],axis=1)
#         df = pd.merge(df2,df,on='user_id',how='left')
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [10]:
feat_setup_2()

D:\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,user_id,sku_id,time,cate,type,age,sex,user_lv_cd,user_reg_tm,test_time,...,9,8,7,6,5,4,3,2,1,load_days
0,296130.0,18412,2016-02-23 12:16:10,8,1,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,296130.0,18412,2016-02-23 12:16:12,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,296130.0,18412,2016-02-23 12:16:13,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,296130.0,18412,2016-02-23 12:16:20,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
4,296130.0,18412,2016-02-23 12:16:22,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
5,217567.0,22387,2016-01-31 23:59:54,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
6,217567.0,22387,2016-01-31 23:59:54,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
7,217567.0,116489,2016-02-01 00:00:53,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
8,217567.0,116489,2016-02-01 00:01:46,8,5,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
9,217567.0,116489,2016-02-01 00:03:20,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
10,217567.0,116489,2016-02-01 00:03:21,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
11,217567.0,17470,2016-02-01 00:03:26,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
12,217567.0,17470,2016-02-01 00:03:26,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
13,217567.0,17470,2016-02-01 00:04:08,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
14,217567.0,17470,2016-02-01 00:04:08,8,5,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
15,217567.0,17470,2016-02-01 00:04:12,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
16,217567.0,116489,2016-02-01 00:04:51,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
17,217567.0,112332,2016-02-24 22:54:41,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
18,217567.0,112332,2016-02-24 22:54:41,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
19,217567.0,112332,2016-02-24 22:54:41,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
20,217567.0,112332,2016-02-24 22:54:41,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
21,217567.0,112332,2016-02-24 22:54:41,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
22,214894.0,154732,2016-02-04 02:06:56,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
23,214894.0,154732,2016-02-04 02:06:56,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
24,214894.0,154732,2016-02-04 02:06:56,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
25,214894.0,154732,2016-02-04 02:06:56,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
26,214894.0,154732,2016-02-04 02:06:56,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
27,214894.0,154732,2016-02-04 02:08:01,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
28,214894.0,154732,2016-02-04 02:08:01,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
29,214894.0,14163,2016-02-04 20:17:59,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1457585,285410.0,15781,2016-02-24 23:58:18,8,6,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457586,285410.0,73469,2016-02-24 23:58:18,8,1,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457587,285410.0,73469,2016-02-24 23:58:18,8,1,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457588,285410.0,15781,2016-02-24 23:58:18,8,6,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457589,285410.0,73469,2016-02-24 23:58:18,8,6,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457590,285410.0,15781,2016-02-24 23:58:48,8,6,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457591,297671.0,81462,2016-02-24 23:51:06,8,6,36-45岁,0.0,4,2015-11-12,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457592,297671.0,81462,2016-02-24 23:51:06,8,1,36-45岁,0.0,4,2015-11-12,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457593,297671.0,81462,2016-02-24 23:51:06,8,6,36-45岁,0.0,4,2015-11-12,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457594,297671.0,81462,2016-02-24 23:51:06,8,1,36-45岁,0.0,4,2015-11-12,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457595,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457596,303930.0,154636,2016-02-24 23:54:12,8,6,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457597,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457598,303930.0,154636,2016-02-24 23:54:12,8,6,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457599,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457600,303930.0,154636,2016-02-24 23:54:12,8,6,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457601,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457602,261230.0,142477,2016-02-24 23:55:24,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457603,261230.0,142477,2016-02-24 23:55:24,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457604,261230.0,142477,2016-02-24 23:55:24,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457605,261230.0,142477,2016-02-24 23:55:24,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457606,261230.0,142477,2016-02-24 23:55:24,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457607,261230.0,142477,2016-02-24 23:55:54,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457608,261230.0,142477,2016-02-24 23:55:54,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457609,261230.0,142477,2016-02-24 23:56:54,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457610,285579.0,44854,2016-02-24 23:59:05,8,1,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457611,285579.0,44854,2016-02-24 23:59:05,8,6,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457612,285579.0,44854,2016-02-24 23:59:05,8,6,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457613,285579.0,44854,2016-02-24 23:59:05,8,6,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1457614,285579.0,44854,2016-02-24 23:59:05,8,1,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0

In [11]:
#第一次登录距离预测第一天的距离(天)
def feat_setup_3():
    dump_path = './cache/feat_setup_3'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        dataset = feat_setup_2()
        df = dataset[['user_id','time']]
        df= df.groupby('user_id',as_index=False).time.min()
        df.columns = ['user_id','first_time']
        df['first_time'] = df.first_time.apply(lambda t:t[:10])
#         df = df.drop(['time'],axis=1)
        df = df.drop_duplicates()
        df['first_time'] = pd.to_datetime(df['first_time'],format='%Y-%m-%d')
        df['pre_time'] = '2016-02-26'
        df['pre_time'] = pd.to_datetime(df['pre_time'],format='%Y-%m-%d')
        df['first_lo_dis'] = (df['pre_time'] - df['first_time']).apply(lambda t:t.total_seconds()/60/60/24)
        df = df.drop(['pre_time','first_time'],axis=1)
        df = pd.merge(dataset,df,on='user_id',how='left')
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [100]:
# dataset = feat_setup_2()
# df = dataset[['user_id','time']]
# df= df.groupby('user_id',as_index=False).time.min()
# df.columns = ['user_id','first_time']
# df['first_time'] = df.first_time.apply(lambda t:t[:10])
# #         df = df.drop(['time'],axis=1)
# df = df.drop_duplicates()
# # df['first_time'] = pd.to_datetime(df['first_time'],format='%Y-%m-%d')
# end_date = '2016-02-25 00:00:00'

# # df['pre_time'] = pd.to_datetime(df['pre_time'],format='%Y-%m-%d')
# df['first_lo_dis'] = df.first_time.apply(lambda t:(pd.to_datetime(end_date)-t).total_seconds()/60/60/24)
# df = df.drop(['first_time'],axis=1)
# df = pd.merge(dataset,df,on='user_id',how='left')
# df

#明天来处理

In [12]:
feat_setup_3()

,user_id,sku_id,time,cate,type,age,sex,user_lv_cd,user_reg_tm,test_time,...,8,7,6,5,4,3,2,1,load_days,first_lo_dis
0,296130.0,18412,2016-02-23 12:16:10,8,1,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3.0
1,296130.0,18412,2016-02-23 12:16:12,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3.0
2,296130.0,18412,2016-02-23 12:16:13,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3.0
3,296130.0,18412,2016-02-23 12:16:20,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3.0
4,296130.0,18412,2016-02-23 12:16:22,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3.0
5,217567.0,22387,2016-01-31 23:59:54,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
6,217567.0,22387,2016-01-31 23:59:54,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
7,217567.0,116489,2016-02-01 00:00:53,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
8,217567.0,116489,2016-02-01 00:01:46,8,5,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
9,217567.0,116489,2016-02-01 00:03:20,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
10,217567.0,116489,2016-02-01 00:03:21,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
11,217567.0,17470,2016-02-01 00:03:26,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
12,217567.0,17470,2016-02-01 00:03:26,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
13,217567.0,17470,2016-02-01 00:04:08,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
14,217567.0,17470,2016-02-01 00:04:08,8,5,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
15,217567.0,17470,2016-02-01 00:04:12,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
16,217567.0,116489,2016-02-01 00:04:51,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
17,217567.0,112332,2016-02-24 22:54:41,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
18,217567.0,112332,2016-02-24 22:54:41,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
19,217567.0,112332,2016-02-24 22:54:41,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
20,217567.0,112332,2016-02-24 22:54:41,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
21,217567.0,112332,2016-02-24 22:54:41,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0
22,214894.0,154732,2016-02-04 02:06:56,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0
23,214894.0,154732,2016-02-04 02:06:56,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0
24,214894.0,154732,2016-02-04 02:06:56,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0
25,214894.0,154732,2016-02-04 02:06:56,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0
26,214894.0,154732,2016-02-04 02:06:56,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0
27,214894.0,154732,2016-02-04 02:08:01,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0
28,214894.0,154732,2016-02-04 02:08:01,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0
29,214894.0,14163,2016-02-04 20:17:59,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1457585,285410.0,15781,2016-02-24 23:58:18,8,6,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457586,285410.0,73469,2016-02-24 23:58:18,8,1,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457587,285410.0,73469,2016-02-24 23:58:18,8,1,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457588,285410.0,15781,2016-02-24 23:58:18,8,6,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457589,285410.0,73469,2016-02-24 23:58:18,8,6,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457590,285410.0,15781,2016-02-24 23:58:48,8,6,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457591,297671.0,81462,2016-02-24 23:51:06,8,6,36-45岁,0.0,4,2015-11-12,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457592,297671.0,81462,2016-02-24 23:51:06,8,1,36-45岁,0.0,4,2015-11-12,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457593,297671.0,81462,2016-02-24 23:51:06,8,6,36-45岁,0.0,4,2015-11-12,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457594,297671.0,81462,2016-02-24 23:51:06,8,1,36-45岁,0.0,4,2015-11-12,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457595,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457596,303930.0,154636,2016-02-24 23:54:12,8,6,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457597,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457598,303930.0,154636,2016-02-24 23:54:12,8,6,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457599,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457600,303930.0,154636,2016-02-24 23:54:12,8,6,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457601,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457602,261230.0,142477,2016-02-24 23:55:24,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457603,261230.0,142477,2016-02-24 23:55:24,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457604,261230.0,142477,2016-02-24 23:55:24,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457605,261230.0,142477,2016-02-24 23:55:24,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457606,261230.0,142477,2016-02-24 23:55:24,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457607,261230.0,142477,2016-02-24 23:55:54,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457608,261230.0,142477,2016-02-24 23:55:54,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457609,261230.0,142477,2016-02-24 23:56:54,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457610,285579.0,44854,2016-02-24 23:59:05,8,1,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457611,285579.0,44854,2016-02-24 23:59:05,8,6,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457612,285579.0,44854,2016-02-24 23:59:05,8,6,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457613,285579.0,44854,2016-02-24 23:59:05,8,6,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
1457614,285579.0,44854,2016-02-24 23:59:05,8,1,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0

In [13]:
#最后一次浏览第8类商品时间与预测第一天距离（秒）
def feat_setup_4(start_time='2016-01-31 00:00:00',end_time = '2016-02-25 00:00:00'):
    dump_path = './cache/feat_setup_4'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        dataset = feat_setup_3()
        df = dataset[['user_id','time']]
        df = df.groupby('user_id',as_index=False).time.max()
        df['time'] = pd.to_datetime(df.time)
        df['last_tm_dis'] = df.time.apply(lambda t:(pd.to_datetime(end_time) - t).total_seconds())
        df = df.drop(['time'],axis=1)
        df = df.drop_duplicates()
        df = pd.merge(dataset,df,on='user_id',how='left')
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [14]:
feat_setup_4()

,user_id,sku_id,time,cate,type,age,sex,user_lv_cd,user_reg_tm,test_time,...,7,6,5,4,3,2,1,load_days,first_lo_dis,last_tm_dis
0,296130.0,18412,2016-02-23 12:16:10,8,1,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3.0,128618.0
1,296130.0,18412,2016-02-23 12:16:12,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3.0,128618.0
2,296130.0,18412,2016-02-23 12:16:13,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3.0,128618.0
3,296130.0,18412,2016-02-23 12:16:20,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3.0,128618.0
4,296130.0,18412,2016-02-23 12:16:22,8,6,16-25岁,2.0,2,2015-11-07,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3.0,128618.0
5,217567.0,22387,2016-01-31 23:59:54,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
6,217567.0,22387,2016-01-31 23:59:54,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
7,217567.0,116489,2016-02-01 00:00:53,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
8,217567.0,116489,2016-02-01 00:01:46,8,5,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
9,217567.0,116489,2016-02-01 00:03:20,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
10,217567.0,116489,2016-02-01 00:03:21,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
11,217567.0,17470,2016-02-01 00:03:26,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
12,217567.0,17470,2016-02-01 00:03:26,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
13,217567.0,17470,2016-02-01 00:04:08,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
14,217567.0,17470,2016-02-01 00:04:08,8,5,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
15,217567.0,17470,2016-02-01 00:04:12,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
16,217567.0,116489,2016-02-01 00:04:51,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
17,217567.0,112332,2016-02-24 22:54:41,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
18,217567.0,112332,2016-02-24 22:54:41,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
19,217567.0,112332,2016-02-24 22:54:41,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
20,217567.0,112332,2016-02-24 22:54:41,8,6,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
21,217567.0,112332,2016-02-24 22:54:41,8,1,36-45岁,0.0,5,2007-06-04,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,26.0,3919.0
22,214894.0,154732,2016-02-04 02:06:56,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0,4922.0
23,214894.0,154732,2016-02-04 02:06:56,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0,4922.0
24,214894.0,154732,2016-02-04 02:06:56,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0,4922.0
25,214894.0,154732,2016-02-04 02:06:56,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0,4922.0
26,214894.0,154732,2016-02-04 02:06:56,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0,4922.0
27,214894.0,154732,2016-02-04 02:08:01,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0,4922.0
28,214894.0,154732,2016-02-04 02:08:01,8,1,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0,4922.0
29,214894.0,14163,2016-02-04 20:17:59,8,6,26-35岁,0.0,5,2010-11-15,2016-02-25,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0,22.0,4922.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1457585,285410.0,15781,2016-02-24 23:58:18,8,6,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,72.0
1457586,285410.0,73469,2016-02-24 23:58:18,8,1,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,72.0
1457587,285410.0,73469,2016-02-24 23:58:18,8,1,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,72.0
1457588,285410.0,15781,2016-02-24 23:58:18,8,6,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,72.0
1457589,285410.0,73469,2016-02-24 23:58:18,8,6,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,72.0
1457590,285410.0,15781,2016-02-24 23:58:48,8,6,-1,1.0,5,2012-11-18,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,72.0
1457591,297671.0,81462,2016-02-24 23:51:06,8,6,36-45岁,0.0,4,2015-11-12,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,534.0
1457592,297671.0,81462,2016-02-24 23:51:06,8,1,36-45岁,0.0,4,2015-11-12,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,534.0
1457593,297671.0,81462,2016-02-24 23:51:06,8,6,36-45岁,0.0,4,2015-11-12,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,534.0
1457594,297671.0,81462,2016-02-24 23:51:06,8,1,36-45岁,0.0,4,2015-11-12,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,534.0
1457595,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,348.0
1457596,303930.0,154636,2016-02-24 23:54:12,8,6,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,348.0
1457597,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,348.0
1457598,303930.0,154636,2016-02-24 23:54:12,8,6,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,348.0
1457599,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,348.0
1457600,303930.0,154636,2016-02-24 23:54:12,8,6,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,348.0
1457601,303930.0,154636,2016-02-24 23:54:12,8,1,16-25岁,2.0,3,2016-01-14,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,348.0
1457602,261230.0,142477,2016-02-24 23:55:24,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,186.0
1457603,261230.0,142477,2016-02-24 23:55:24,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,186.0
1457604,261230.0,142477,2016-02-24 23:55:24,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,186.0
1457605,261230.0,142477,2016-02-24 23:55:24,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,186.0
1457606,261230.0,142477,2016-02-24 23:55:24,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,186.0
1457607,261230.0,142477,2016-02-24 23:55:54,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,186.0
1457608,261230.0,142477,2016-02-24 23:55:54,8,1,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,186.0
1457609,261230.0,142477,2016-02-24 23:56:54,8,6,26-35岁,1.0,5,2014-11-25,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,186.0
1457610,285579.0,44854,2016-02-24 23:59:05,8,1,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,55.0
1457611,285579.0,44854,2016-02-24 23:59:05,8,6,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,55.0
1457612,285579.0,44854,2016-02-24 23:59:05,8,6,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,55.0
1457613,285579.0,44854,2016-02-24 23:59:05,8,6,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,55.0
1457614,285579.0,44854,2016-02-24 23:59:05,8,1,36-45岁,0.0,3,2012-11-19,2016-02-25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,55.0

In [15]:
#写不出来，过两天再写


#用户前（1/2/3/5/7）天的有效行为时间(单位：秒)
def feat_setup_5():
    dump_path = './cache/feat_setup_5'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        dataset = feat_setup_4()
        df = dataset[['user_id','time']]
        #前一天有效行为时间
        df1 = df[df['time']>'2016-02-24 00:00:00']
        df2 = df1.groupby('user_id',as_index=False).time.min()
        df2['time'] = pd.to_datetime(df2.time,format='%Y-%m-%d')
        df3 = df.groupby('user_id',as_index=False).time.max()
        df3.columns = ['user_id','max_time']
        df3['max_time'] = pd.to_datetime(df3.max_time,format='%Y-%m-%d')
        df3 = pd.merge(df2,df3,on='user_id',how='left')
        df3['belong_1_day'] = (df3['max_time'] - df3['time']).apply(lambda t:t.total_seconds())
        df3 = df3[['user_id','belong_1_day']].drop_duplicates()
        dataset = pd.merge(dataset,df3,on='user_id',how='left')
        
        #前两天有效时间
        df = dataset[['user_id','time']]
        df1 = df[(df['time']>'2016-02-23 00:00:00')&(df['time']<'2016-02-24 00:00:00')]
        df2 = df1.groupby('user_id',as_index=False).time.min()
        df2['time'] = pd.to_datetime(df2.time,format='%Y-%m-%d')
        df3 = df.groupby('user_id',as_index=False).time.max()
        df3.columns = ['user_id','max_time']
        df3['max_time'] = pd.to_datetime(df3.max_time,format='%Y-%m-%d')
        df3 = pd.merge(df2,df3,on='user_id',how='left')
        df3['belong_2_day'] = (df3['max_time'] - df3['time']).apply(lambda t:t.total_seconds())
        df3 = df3[['user_id','belong_2_day']].drop_duplicates()
        dataset = pd.merge(dataset,df3,on='user_id',how='left')
        dataset['belong_2_day'] = dataset['belong_2_day'] + dataset['belong_1_day']
        
        # 前3天有效时间
        df = dataset[['user_id','time']]
        df1 = df[(df['time']>'2016-02-22 00:00:00')&(df['time']<'2016-02-23 00:00:00')]
        df2 = df1.groupby('user_id',as_index=False).time.min()
        df2['time'] = pd.to_datetime(df2.time,format='%Y-%m-%d')
        df3 = df.groupby('user_id',as_index=False).time.max()
        df3.columns = ['user_id','max_time']
        df3['max_time'] = pd.to_datetime(df3.max_time,format='%Y-%m-%d')
        df3 = pd.merge(df2,df3,on='user_id',how='left')
        df3['belong_3_day'] = (df3['max_time'] - df3['time']).apply(lambda t:t.total_seconds())
        df3 = df3[['user_id','belong_3_day']].drop_duplicates()
        dataset = pd.merge(dataset,df3,on='user_id',how='left')
        dataset['belong_3_day'] = dataset['belong_3_day'] + dataset['belong_2_day']
        
        #前4天有效行为时间
        df = dataset[['user_id','time']]
        df1 = df[(df['time']>'2016-02-21 00:00:00')&(df['time']<'2016-02-22 00:00:00')]
        df2 = df1.groupby('user_id',as_index=False).time.min()
        df2['time'] = pd.to_datetime(df2.time,format='%Y-%m-%d')
        df3 = df.groupby('user_id',as_index=False).time.max()
        df3.columns = ['user_id','max_time']
        df3['max_time'] = pd.to_datetime(df3.max_time,format='%Y-%m-%d')
        df3 = pd.merge(df2,df3,on='user_id',how='left')
        df3['belong_4_day'] = (df3['max_time'] - df3['time']).apply(lambda t:t.total_seconds())
        df3 = df3[['user_id','belong_4_day']].drop_duplicates()
        dataset = pd.merge(dataset,df3,on='user_id',how='left')
        dataset['belong_4_day'] = dataset['belong_4_day'] + dataset['belong_3_day']
        
        #前5天有效行为时间
        df = dataset[['user_id','time']]
        df1 = df[(df['time']>'2016-02-20 00:00:00')&(df['time']<'2016-02-21 00:00:00')]
        df2 = df1.groupby('user_id',as_index=False).time.min()
        df2['time'] = pd.to_datetime(df2.time,format='%Y-%m-%d')
        df3 = df.groupby('user_id',as_index=False).time.max()
        df3.columns = ['user_id','max_time']
        df3['max_time'] = pd.to_datetime(df3.max_time,format='%Y-%m-%d')
        df3 = pd.merge(df2,df3,on='user_id',how='left')
        df3['belong_5_day'] = (df3['max_time'] - df3['time']).apply(lambda t:t.total_seconds())
        df3 = df3[['user_id','belong_5_day']].drop_duplicates()
        dataset = pd.merge(dataset,df3,on='user_id',how='left')
        dataset['belong_5_day'] = dataset['belong_5_day'] + dataset['belong_4_day']
        df = dataset[['user_id','belong_1_day','belong_2_day','belong_3_day','belong_4_day','belong_5_day']].drop_duplicates()
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
        
    return df

In [16]:
a = feat_setup_5()
a.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23312 entries, 0 to 1457610
Data columns (total 6 columns):
user_id         23312 non-null float64
belong_1_day    5707 non-null float64
belong_2_day    1109 non-null float64
belong_3_day    392 non-null float64
belong_4_day    144 non-null float64
belong_5_day    65 non-null float64
dtypes: float64(6)
memory usage: 1.2 MB

In [20]:
# dataset = feat_setup_2()
# df = dataset[['user_id','time']]
#         #前一天有效行为时间
# df1 = df[df['time']>'2016-02-24 00:00:00']
# df2 = df1.groupby('user_id',as_index=False).time.min()
# df2['time'] = pd.to_datetime(df2.time,format='%Y-%m-%d %H:%M:%S')
# df3 = df.groupby('user_id',as_index=False).time.max()
# df3.columns = ['user_id','max_time']
# # df3 = pd.merge(df2,df3,on='user_id',how='left')
# df3['belong_1_day'] = df3.time.apply(lambda t:(pd.to_datetime(df3.max_time)-t).total_seconds())
# df3

a= {'data':['2016-02-03 00:10:00'],'test':['2016-02-03 00:12:30']}
a = pd.DataFrame(a)
a['data'] = pd.to_datetime(a.data,format='%Y-%m-%d')
a['test'] = pd.to_datetime(a.test,format='%Y-%m-%d')

a['a'] = (a['test'] -a['data']).apply(lambda t: t.total_seconds())
a

                 data                test      a
0 2016-02-03 00:10:00 2016-02-03 00:12:30  150.0

# 用户行为特征

In [29]:
#用户前（7/15/26天）第八类商品的操作数
def feat_setup_6():
    dump_path = './cache/feat_setup_6'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        dataset = feat_setup_5()
        #用户前7天对第八类商品的操作数
        df = dataset[dataset['time']>'2016-02-18 00:00:00'][['user_id','type']]
        df = df.groupby('user_id',as_index=False).count()
        df.columns = ['user_id','last_7']
        #用户前15天对第八类商品的操作数
        df1 = dataset[dataset['time']>'2016-02-10 00:00:00'][['user_id','type']]
        df1 = df1.groupby('user_id',as_index=False).count()
        df1.columns = ['user_id','last_15']
        #用户前26天对第八类商品的操作数
        df2 = dataset[['user_id','type']]
        df2 = df2.groupby('user_id',as_index=False).count()
        df2.columns = ['user_id','last_26']
        dataset = pd.merge(dataset,df,on='user_id',how='left')
        dataset = pd.merge(dataset,df1,on='user_id',how='left')
        df = pd.merge(dataset,df2,on='user_id',how='left')
        df = df.fillna(0)
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [30]:
feat_setup_6()

KeyError: 'time'

In [ ]:
#用户前7/15/26天的所有操作数
def feat_setup_7():
    dump_path = './cache/feat_setup_7'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        dataset = Action_useful_user()
        df = dataset[dataset['time']>'2016-02-18 00:00:00'][['user_id','type']]
        #用户前7天总操作数
        df = df.groupby('user_id',as_index = False).count()
        df.columns = ['user_id','last_7_all']
        #用户前15天总操作数
        df1 = dataset[dataset['time']>'2016-02-10 00:00:00'][['user_id','type']]
        df1 = df1.groupby('user_id',as_index=False).count()
        df1.columns = ['user_id','last_15_all']
        #用户总操作数
        df2 = dataset[['user_id','type']]
        df2 = df2.groupby('user_id',as_index=False).count()
        df2.columns = ['user_id','last_26_all']
        dataset = pd.DataFrame(dataset['user_id']).drop_duplicates()
        dataset = pd.merge(dataset,df,on='user_id',how='left')
        dataset = pd.merge(dataset,df1,on='user_id',how='left')
        dataset = pd.merge(dataset,df2,on='user_id',how='left')
        
        df = feat_setup_6()
        df = pd.merge(df,dataset,on='user_id',how='left')
        df = df.fillna(0)
        df['ratio_7'] = df['last_7'] / df['last_7_all']
        df['ratio_15'] = df['last_15'] / df['last_15_all']
        df['ratio_26'] = df['last_26'] / df['last_26_all']
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [ ]:
feat_setup_7()

In [ ]:
#用户前7天加购物车/删除购物车/关注统计
def feat_setup_8():
    dump_path ='./cache/feat_setup_8'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        dataset = feat_setup_7()
        df = dataset[dataset['time']>'2016-02-18 00:00:00'][['user_id','type']]
        df_2 = df[df['type']==2]
        df_3 = df[df['type']==3]
        df_4 = df[df['type']==5]
        df_2 = df_2.groupby('user_id',as_index=False).count()
        df_2.columns = ['user_id','cart_num']
        df_3 = df_3.groupby('user_id',as_index=False).count()
        df_3.columns = ['user_id','delte_num']
        df_4 = df_4.groupby('user_id',as_index=False).count()
        df_4.columns = ['user_id','like_num']
        dataset = pd.merge(dataset,df_2,on='user_id',how='left')
        dataset = pd.merge(dataset,df_3,on='user_id',how='left')
        df = pd.merge(dataset,df_4,on='user_id',how='left')
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [31]:
feat_setup_8()

KeyError: 'time'

In [ ]:
#预测前7/15天浏览第8类商品天数
def feat_setup_9():
    dump_path = './cache/feat_setup_9'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        dataset = feat_setup_8()
        #前七天登陆天数（查看第8类商品）
        df = dataset[['user_id','7','6','5','4','3','2','1']].drop_duplicates()
        df['cate_8_days/7'] = df.sum(axis=1) - df['user_id']
        df = df[['user_id','cate_8_days/7']]
        #前15天........
        df1 = dataset[['user_id','15','14','13','12','11','10','9','8','7','6','5','4','3','2','1']].drop_duplicates()
        df1['cate_8_days/15'] = df1.sum(axis=1) - df1['user_id']
        df1 = df1[['user_id','cate_8_days/15']]
        dataset = pd.merge(dataset,df,on='user_id',how='left')
        df = pd.merge(dataset,df1,on='user_id',how='left')
        
        #前7天/15天总的登陆天数
        data = Action_useful_user()[['user_id','time']]
        data = data[(data['time']>'2016-02-10 00:00:00')&(data['time']<'2016-02-25 00:00:00')]
        data['time'] = data.time.apply(lambda t:t[:10])
        data = data.drop_duplicates()
        type_dummies = pd.get_dummies(data['time'],prefix=None)
        #for i in range(0,15):
            #type_dummies.columns[i] = ['i+1']
        type_dummies.columns = ['15','14','13','12','11','10','9','8','7','6','5','4','3','2','1']
        data = pd.concat([data,type_dummies],axis=1)
        data = data.drop(['time'],axis=1)
        data = data.groupby('user_id',as_index=False).sum()

        #前15天登录天数
        data['15_days_load'] = data.sum(axis=1) - data['user_id']
        #前7天登录天数
        data = data[['user_id','7','6','5','4','3','2','1','15_days_load']]
        data['7_days_load'] = data.sum(axis=1) - data['user_id'] - data['15_days_load']
        data = data[['user_id','7_days_load','15_days_load']]
        
        #两张表拼接
        df = pd.merge(df,data,on='user_id',how='left')
        df['ratio_cate_8/7'] = df['cate_8_days/7'] / df['7_days_load']
        df['ratio_cate_8/15'] = df['cate_8_days/15'] / df['15_days_load']
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [ ]:
feat_setup_9()

# 人工规则

In [ ]:
#用户仅仅在预测前两天登录过，并且登陆天数==1
def feat_rule_1():
    dump_path = './cache/feat_rule_1'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        dataset = feat_setup_9()
        df = dataset[dataset['time']>'2016-02-23 00:00:00']
        df = df[df['load_days']==1]
        df['label_1'] = 1
        df = df[['user_id','label_1']].drop_duplicates()
        dataset = pd.merge(dataset,df,on='user_id',how='left')
        #预测前三天加入过购物车、删除购物车、关注的用户
        df = dataset[dataset['time']>'2016-02-22 00:00:00']
        df = df[df['cate']==8]
        df = df[(df['type']==2)|(df['type']==3)|(df['type']==5)]
        df['label_2'] = 1
        df = df[['user_id','label_2']].drop_duplicates()
        df = pd.merge(dataset,df,on='user_id',how='left')
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [ ]:
feat_rule_1()

In [13]:
#用户前七天最大单秒点击频率
# dataset = feat_setup_9()[['user_id','sku_id']]
# dataset['label'] = np.nan
# dataset = dataset.groupby(['user_id','sku_id'],as_index=False).size().reset_index(name='num_model_click')
# dataset = dataset[['user_id','num_model_click']]
# dataset = dataset.groupby('user_id',as_index=False).num_model_click.max()
# dataset.columns = ['user_id','max_click_num']

        user_id  num_model_click
0      200016.0               51
1      200022.0                6
2      200027.0               53
3      200030.0               15
4      200031.0                9
5      200033.0                4
6      200044.0               10
7      200045.0              116
8      200046.0               39
9      200047.0               13
10     200052.0               10
11     200056.0               19
12     200061.0                7
13     200067.0                6
14     200073.0                5
15     200085.0               32
16     200087.0               11
17     200089.0               36
18     200092.0                4
19     200095.0               26
20     200096.0                7
21     200104.0               45
22     200109.0               13
23     200119.0                5
24     200131.0               12
25     200139.0               37
26     200142.0                5
27     200143.0                9
28     200144.0                7
29     200150.0                4
...         ...              ...
20996  305185.0                5
20997  305189.0                4
20998  305191.0                6
20999  305200.0                4
21000  305217.0               25
21001  305218.0               14
21002  305225.0               14
21003  305228.0                7
21004  305232.0               57
21005  305236.0                6
21006  305246.0                5
21007  305249.0                3
21008  305250.0               10
21009  305257.0               31
21010  305262.0                8
21011  305265.0                3
21012  305268.0                2
21013  305273.0               78
21014  305278.0               26
21015  305280.0               10
21016  305283.0              224
21017  305289.0               20
21018  305291.0               16
21019  305292.0               26
21020  305294.0               12
21021  305297.0                8
21022  305298.0               10
21023  305300.0               23
21024  305302.0               10
21025  305321.0                2

[21026 rows x 2 columns]

# 用训练集，测试集构建模型

In [33]:
#提取关键特征，构建模型
def user_train_model():
    dump_path = './cache/user_train_model_data'
    if os.path.exists(dump_path):
        with open(dump_path,'rb') as f:
            df = pickle.load(f)
    else:
        dataset = feat_rule_1()
#         df = feat_setup_5()
#         dataset = pd.merge(dataset,df,on='user_id',how='left')
        dataset = dataset.drop(['sku_id','time','type','25','24','23','22','21','20','19','18','17','16','15','14','13','12','11','10','9','8','7','6','5','4','3','2','1'],axis=1)
        dataset = dataset.drop(['cate','user_reg_tm','test_time'],axis=1)
        with open(dump_path,'wb') as f:
            pickle.dump(df,f)
    return df

In [35]:
user_train_model()

KeyError: 'time'

In [ ]:
# train_x = user_train_model()
# train_x
# # test_x = pd.read_csv('test_dataset.csv').user_id.to_frame().drop_duplicates()
# # test_x
# test_x['label'] = 1
# train_x = pd.merge(train_x,test_x,on='user_id',how='left')
train_x= train_x.fillna(0)

train_x.T

In [ ]:
import xgboost as xgb
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_x, train_x.label.values, test_size=0.2, random_state=1)
dtrain = xgb.DMatrix(X_train.drop(['user_id', 'label',"reg_dis",'age','first_lo_dis'], axis=1), label=y_train)
dtest = xgb.DMatrix(X_test.drop(['user_id', 'label','reg_dis','age','first_lo_dis'], axis=1), label=y_test)
dvalid = xgb.DMatrix(X_test.drop(['user_id', 'label','reg_dis','age','first_lo_dis'], axis=1))

param = {'learning_rate' : 0.1, 'n_estimators': 500, 'max_depth': 3, 
        'min_child_weight': 5, 'gamma': 0.2, 'subsample': 1, 'colsample_bytree': 0.8,
        'scale_pos_weight': 1, 'eta': 0.05, 'silent': 0, 'objective': 'binary:logistic','booster': 'gbtree'}
num_round = 70
# 89
param['nthread'] = -1
param['eval_metric'] = "logloss"
evallist = [(dtest, 'test'), (dtrain, 'train')]
bst = xgb.train(params=param, dtrain=dtrain, num_boost_round=num_round, evals=evallist, early_stopping_rounds=10)

predict = bst.predict(dvalid)

In [111]:
a = pd.DataFrame(predict)
a = a.sort_values(by=0,ascending=False)
a[:500]

             0
4662  0.563708
4661  0.431620
4660  0.289504
4659  0.285175
4658  0.228577
4657  0.211187
4656  0.188477
4655  0.186477
4654  0.184311
4653  0.178360
4652  0.165591
4651  0.151583
4650  0.151231
4649  0.148616
4648  0.146862
4647  0.137272
4646  0.134582
4645  0.128680
4644  0.124558
4643  0.123865
4642  0.122754
4641  0.121147
4640  0.120303
4639  0.117323
4638  0.114976
4637  0.114803
4636  0.113209
4635  0.112940
4634  0.111370
4633  0.110639
...        ...
4192  0.025760
4191  0.025755
4190  0.025750
4189  0.025725
4188  0.025674
4187  0.025654
4186  0.025625
4185  0.025619
4184  0.025553
4183  0.025535
4182  0.025517
4181  0.025485
4180  0.025472
4179  0.025426
4178  0.025381
4177  0.025358
4176  0.025345
4175  0.025342
4174  0.025340
4173  0.025315
4172  0.025251
4171  0.025251
4170  0.025237
4169  0.025206
4168  0.025169
4167  0.025163
4166  0.025117
4165  0.025068
4164  0.025036
4163  0.025017

[500 rows x 1 columns]

In [14]:
# a = '2016-01-01'
# a = dt.datetime.strptime(a,'%Y-%m-%d')
# b ='2016-04-03'
# b = dt.datetime.strptime(b,'%Y-%m-%d')

# (b-a).days
# a=pd.read_csv(USER_FILE,encoding='gbk')
# a

b = feat_setup_1()[['user_id','sku_id','time']]
b.columns = ['1','2','3']
b

                1       2                    3
0        296130.0   18412  2016-02-23 12:16:10
1        296130.0   18412  2016-02-23 12:16:12
2        296130.0   18412  2016-02-23 12:16:13
3        296130.0   18412  2016-02-23 12:16:20
4        296130.0   18412  2016-02-23 12:16:22
5        217567.0   22387  2016-01-31 23:59:54
6        217567.0   22387  2016-01-31 23:59:54
7        217567.0  116489  2016-02-01 00:00:53
8        217567.0  116489  2016-02-01 00:01:46
9        217567.0  116489  2016-02-01 00:03:20
10       217567.0  116489  2016-02-01 00:03:21
11       217567.0   17470  2016-02-01 00:03:26
12       217567.0   17470  2016-02-01 00:03:26
13       217567.0   17470  2016-02-01 00:04:08
14       217567.0   17470  2016-02-01 00:04:08
15       217567.0   17470  2016-02-01 00:04:12
16       217567.0  116489  2016-02-01 00:04:51
17       217567.0  112332  2016-02-24 22:54:41
18       217567.0  112332  2016-02-24 22:54:41
19       217567.0  112332  2016-02-24 22:54:41
20       217567.0  112332  2016-02-24 22:54:41
21       217567.0  112332  2016-02-24 22:54:41
22       214894.0  154732  2016-02-04 02:06:56
23       214894.0  154732  2016-02-04 02:06:56
24       214894.0  154732  2016-02-04 02:06:56
25       214894.0  154732  2016-02-04 02:06:56
26       214894.0  154732  2016-02-04 02:06:56
27       214894.0  154732  2016-02-04 02:08:01
28       214894.0  154732  2016-02-04 02:08:01
29       214894.0   14163  2016-02-04 20:17:59
...           ...     ...                  ...
1349632  285410.0   15781  2016-02-24 23:58:18
1349633  285410.0   73469  2016-02-24 23:58:18
1349634  285410.0   73469  2016-02-24 23:58:18
1349635  285410.0   15781  2016-02-24 23:58:18
1349636  285410.0   73469  2016-02-24 23:58:18
1349637  285410.0   15781  2016-02-24 23:58:48
1349638  297671.0   81462  2016-02-24 23:51:06
1349639  297671.0   81462  2016-02-24 23:51:06
1349640  297671.0   81462  2016-02-24 23:51:06
1349641  297671.0   81462  2016-02-24 23:51:06
1349642  303930.0  154636  2016-02-24 23:54:12
1349643  303930.0  154636  2016-02-24 23:54:12
1349644  303930.0  154636  2016-02-24 23:54:12
1349645  303930.0  154636  2016-02-24 23:54:12
1349646  303930.0  154636  2016-02-24 23:54:12
1349647  303930.0  154636  2016-02-24 23:54:12
1349648  303930.0  154636  2016-02-24 23:54:12
1349649  261230.0  142477  2016-02-24 23:55:24
1349650  261230.0  142477  2016-02-24 23:55:24
1349651  261230.0  142477  2016-02-24 23:55:24
1349652  261230.0  142477  2016-02-24 23:55:24
1349653  261230.0  142477  2016-02-24 23:55:24
1349654  261230.0  142477  2016-02-24 23:55:54
1349655  261230.0  142477  2016-02-24 23:55:54
1349656  261230.0  142477  2016-02-24 23:56:54
1349657  285579.0   44854  2016-02-24 23:59:05
1349658  285579.0   44854  2016-02-24 23:59:05
1349659  285579.0   44854  2016-02-24 23:59:05
1349660  285579.0   44854  2016-02-24 23:59:05
1349661  285579.0   44854  2016-02-24 23:59:05

[1320246 rows x 3 columns]

In [4]:
# #统计所有用户最近一次登陆距离预测第一天的距离（天）
# def future_1():
#     dump_path = './cache/Action_userful_load_info'
#     if os.path.exists(dump_path):
#         with open(dump_path,'rb') as f:
#             df = pickle.load(f)
#     else:
#         df = Action_useful_user()
#         df['time'] = df.time.apply(lambda t: t[:10])
# #         #最后一次购买时间
# #         df['last_buy_time'] = df[df['type']==4]
#         df_1 = df.drop_duplicates()
#         type_dummies = pd.get_dummies(df_1['time'],prefix=None)
#         type_dummies.columns = [x for x in range(type_dummies.shape[1])]#    能不能直接生成从30到1的数字
#         df_1 = pd.concat([df_1,type_dummies],axis=0)
#         df_1 =df_1.drop(['sku_id','time','cate','type'],axis=1)
#         df_1 = df_1.groupby('user_id',as_index=False).count()
#         df_1['load_days'] = df_1.sum(axis=1) -df_1.user_id
#         with open()

In [27]:
# dataset = feat_setup_1()
# df = dataset[['user_id','time']]
#         #登录天数
# df['time'] = df.time.apply(lambda t:t[:10])
# df = df.drop_duplicates()
# type_dummies = pd.get_dummies(df['time'],prefix=None)
# type_dummies.columns = ['25','24','23','22','21','20','19','18','17','16','15','14','13','12','11','10','9','8','7','6','5','4','3','2','1']
# df1 = pd.concat([df,type_dummies],axis=1)
# df1 = df1.drop(['time'],axis=1)
# df1 = df1.drop_duplicates()
# df1 = df1.groupby('user_id',as_index=False).sum()
# df1['load_days'] = df1.sum(axis=1) - df1['user_id']
# df1

,user_id,25,24,23,22,21,20,19,18,17,...,9,8,7,6,5,4,3,2,1,load_days
0,200016.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,8.0
1,200022.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,200027.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,5.0
3,200030.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,7.0
4,200031.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
5,200033.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
6,200044.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
7,200045.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,9.0
8,200046.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,4.0
9,200047.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,4.0
10,200052.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0
11,200056.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0
12,200061.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
13,200067.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
14,200073.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0
15,200085.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
16,200087.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
17,200089.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,5.0
18,200092.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
19,200095.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0
20,200096.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
21,200104.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
22,200109.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
23,200119.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
24,200131.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
25,200139.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0
26,200142.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
27,200143.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
28,200144.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0
29,200150.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20996,305185.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
20997,305189.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
20998,305191.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
20999,305200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
21000,305217.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
21001,305218.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
21002,305225.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.0
21003,305228.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
21004,305232.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0
21005,305236.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
21006,305246.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
21007,305249.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
21008,305250.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
21009,305257.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
21010,305262.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0
21011,305265.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0
21012,305268.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
21013,305273.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,3.0
21014,305278.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5.0
21015,305280.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0
21016,305283.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,10.0
21017,305289.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
21018,305291.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,3.0
21019,305292.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
21020,305294.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,4.0
21021,305297.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0
21022,305298.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0
21023,305300.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,3.0
21024,305302.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0
21025,305321.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0

In [55]:
# a= {'data':['2016-01-01 00:00:00','2016-03-03 12:12:12'],'index':['2017-01-01 00:00:00','2017-01-01 00:00:00']}
# a = pd.DataFrame(a)
# a['data'] = pd.to_datetime(a['data'],format='%Y-%m-%d %H:%M:%S')
# a['index'] = pd.to_datetime(a['index'],format='%Y-%m-%d %H:%M:%S')
# end_date = '2017-01-01 00:00:00'
# a['temp'] = a.data.apply(lambda t:(pd.to_datetime(end_date) - t).total_seconds())
# a

                 data      index        temp
0 2016-01-01 00:00:00 2017-01-01  31622400.0
1 2016-03-03 12:12:12 2017-01-01  26221668.0